// let data = [
//   {
//     id: 1,
//     title: "Chemistry",
//     body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, placeat?",
//     timeStart: "10:00",
//     timeEnd: "12:45",
//     dateDue: "2024-03-22", // 2024-03-22 format is pushed from AddEventModal
//     semester: "Sem 2",
//   },

//   {
//     id: 2,
//     title: "Sports",
//     body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, placeat?",
//     timeStart: "10:00",
//     timeEnd: "05:30",
//     dateDue: "2024-03-22",
//     semester: "Sem 2",
//   },
//   {
//     id: 7,
//     title: "DSA",
//     body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, placeat?",
//     timeStart: "12:22",
//     timeEnd: "08:45",
//     dateDue: "2024-03-22",
//     semester: "Sem 2",
//   },
//   {
//     id: 3,
//     title: "DSA",
//     body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, placeat?",
//     timeStart: "13:22",
//     timeEnd: "08:45",
//     dateDue: "2024-03-22",
//     semester: "Sem 2",
//   },
//   {
//     id: 4,
//     title: "DSA",
//     body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, placeat?",
//     timeStart: "13:00",
//     timeEnd: "08:45",
//     dateDue: "2024-03-22",
//     semester: "Sem 2",
//   },
//   {
//     id: 5,
//     title: "DBMS",
//     body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, placeat?",
//     timeStart: "14:30",
//     timeEnd: "22:45",
//     dateDue: "2024-03-22",
//     semester: "Sem 2",
//   },
//   {
//     id: 6,
//     title: "DBMS",
//     body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, placeat?",
//     timeStart: "22:30",
//     timeEnd: "23:45",
//     dateDue: "2024-03-22",
//     semester: "Sem 2",
//   },
//   {
//     id: 7,
//     title: "DBMS",
//     body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, placeat?",
//     timeStart: "00:30",
//     timeEnd: "23:45",
//     dateDue: "2024-03-22",
//     semester: "Sem 2",
//   },
//   {
//     id: 8,
//     title: "DBMS",
//     body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, placeat?",
//     timeStart: "00:30",
//     timeEnd: "23:45",
//     dateDue: "2024-03-22",
//     semester: "Sem 2",
//   },
//   {
//     id: 9,
//     title: "Business",
//     body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, placeat? Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, placeat?",
//     timeStart: "01:30",
//     timeEnd: "23:45",
//     dateDue: "2024-03-22",
//     semester: "MBA",
//   },
//   {
//     id: 10,
//     title: "AIML",
//     body: "Lorem?",
//     timeStart: "02:30",
//     timeEnd: "23:45",
//     dateDue: "2024-03-22",
//     semester: "Mtech",
//   },
// ];

// export default data;
